name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: cx_ps_tt_cristina_goncalves
          cx_client_id: CX_CLIENT_ID
          cx_client_secret: lZLrVlXy6r24uLf8BAzfdFcymceU3xoF


