- name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with: 
        # Path to SARIF file relative to the root of the repository
        sarif_file: cx_result.sarif
  
variables:
  uses: "Checkmarx/ast-github-action@2.0.14"
  with:
    base_uri: "https://eu.ast.checkmarx.net/"
    cx_tenant: "cx_ps_tt_cristina_goncalves"
    cx_client_id: "CX_CLIENT_ID"
    cx_client_secret: "wqcMeXe9gj3iDxB7hrN2oBCnb750Pny9"
    additional_params: "--report-format sarif --output-path"

